### ISSUE TITLE
libnyquist git tag missing use GIT_TAG fa4e1e37c3278aa3a9439f766e52e0b2db894c55

### ISSUE THREAD

**Issue by sloanyyc** [ArthurSonzogni/smkflow#1]
libnyquist osx build failed
need set GIT_TAG fa4e1e37c3278aa3a9439f766e52e0b2db894c55

FetchContent_Declare(libnyquist
  #GIT_REPOSITORY https://github.com.cnpmjs.org/ArthurSonzogni/libnyquist
  GIT_REPOSITORY https://github.com.cnpmjs.org/ddiakopoulos/libnyquist
  GIT_TAG fa4e1e37c3278aa3a9439f766e52e0b2db894c55
  )

**Comment by ArthurSonzogni** [comment]
Thanks for warning me!

**Comment by ArthurSonzogni** [comment]
I believe everything should be fixed now. Could you please confirm?

**Comment by sloanyyc** [comment]
I think so!
